services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web:
    image: 'node-test:latest'
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

